[build]
  publish = "build"
  command = "bun install && bun run build"

[dev]
  command = "bun run dev"
  port = 8080
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
