services:
  - type: web
    name: homevend-backend
    runtime: node
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: homevend-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://your-frontend-url.com
      - key: PORT
        value: 5000

databases:
  - name: homevend-db
    databaseName: homevend
    user: homevend_user
    plan: free