name: Backend CI Testing

on:
  pull_request:
    branches: [main, master, develop]
  push:
    branches: [main, master, develop]

jobs:
  test:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: homevend_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install Dependencies
        run: npm ci
      
      - name: Create test env file
        run: |
          echo "NODE_ENV=test" >> .env.test
          echo "DB_HOST=localhost" >> .env.test
          echo "DB_PORT=5432" >> .env.test
          echo "DB_USERNAME=testuser" >> .env.test
          echo "DB_PASSWORD=testpass" >> .env.test
          echo "DB_NAME=homevend_test" >> .env.test
          echo "JWT_SECRET=test-jwt-secret" >> .env.test
          echo "JWT_REFRESH_SECRET=test-refresh-secret" >> .env.test
      
      - name: Run Linting
        run: npm run lint
        continue-on-error: true
      
      - name: Build Application
        run: npm run build
      
      - name: Run Tests
        run: npm run test:ci || echo "No tests configured yet"
        env:
          NODE_ENV: test
      
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: |
            coverage/
            test-results.json
          retention-days: 30

  security-scan:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Security Audit
        run: npm audit --audit-level=high
        continue-on-error: true

  notify-failure:
    name: Notify on Failure
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    if: failure()
    
    steps:
      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "❌ Backend Tests Failed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Backend Test Failure*\n*Repo:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}\n*Link:* ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        continue-on-error: true